# System
gpu_num: 0
seed: 999
debug: False
verbose: False

# Train / val
val_size: 0.1

# Data Loader
input_width: 480
input_height: 256
scaler: normalize
num_workers: 16
shuffle: True
drop_last: False

# Model
architecture: DeepLabV3Plus
encoder: timm-regnety_008 #timm-regnety_032 #timm-regnety_016
encoder_weight: imagenet #noisy-student
depth: 5
n_classes: 4
activation: null

# Trainer
n_epochs: 100
batch_size: 32
loss: 
  name: GDLoss # MeanCCELoss
  args:
    weight: [1, 1, 1, 1]
metrics: 
  - miou
  - iou1
  - iou2
  - iou3
earlystopping_target: val_miou
earlystopping_patience: 100
optimizer:
  name: AdamW
  args:
    lr: 5.0e-06
    weight_decay: 5.0e-02
scheduler:
  name: CosineAnnealingLR
  args:
    T_max: 100
    eta_min: 0

# Logging
plot:
  - loss
  - miou
  - iou1
  - iou2
  - iou3
